#!/usr/bin/python3
def raise_exception():
    raise TypeError("Mega's new exception")
